name: Base Build

on:
  push:
    branches: [ master, dev, stage , prod]
  pull_request:
    branches: [ master, dev, stage , prod]

env:
  APP_VERSION: v2.0.${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'


    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.19.6'

    - name: Get dependencies
      run: flutter pub get

    # - name: Run tests
    #   run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Build Apk for Playstore 
      run: flutter build appbundle --release

    - name: Build Web
      run: flutter build web

    - name: Tag version
      run: git tag $APP_VERSION

    - name: Push tag
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        artifacts: "build/app/outputs/apk/release/*, build/app/outputs/bundle/release/*"
        tag: MyMuster_v1.1.${{github.run_number}}
        prerelease: false
  
    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/apk/release/*.apk
    
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/*.aab
